### ISSUE TITLE
fix(pop up): pop up does not work if prior sourcing was cancelled

### ISSUE THREAD

**Issue by peterwht** [r0gue-io/pop-cli#103]
![Screenshot 2024-04-08 at 1 34 27 PM](https://github.com/r0gue-io/pop-cli/assets/23270067/68d4ef26-51e2-4f65-b8fe-3932b462d53b)

**Comment by AlexD10S** [comment]
Notice it too, short answer is to remove: 
```
rm -rf /Users/peter/Library/Caches/pop/.src/polkadot-sdk
```
We can execute this automatically in the tool, if finds this issue.

**Comment by Daanvdplas** [comment]
Yes the pop cli should do it. Encountered it too today

**Comment by AlexD10S** [comment]
I have been testing this and seems fixed after this PR https://github.com/r0gue-io/pop-cli/pull/123 . When we introduced a retry attempt if the first attempt fail (cleaning the working dir when fails).

Closing the issue, reopen if you still experiment the problem.
