### ISSUE TITLE
Zombienet TOML file error when setting up a local relaychain

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-cli#116]
I followed the instructions from the latest Getting Started step in the README file and got an error: Error thrown when running `pop up parachain -f ./zombienet-config.toml` with `zombienet-config.toml` is a generated `toml` config file for Zombienet after running `pop new parachain my-app fpt`
```
◇  Sourcing complete.
│
◐  🚀 Launching local network...                                                                                                                                   └  Could not spawn network: TOML parse error at line 30, column 11
   |
30 |   args = [""]
   |           ^^
the provided argument is invalid and doesn't match Arg::Option or Arg::Flag
```

**Comment by AlexD10S** [comment]
Thanks for trying `pop-cli` and reporting the issue.
We are not parsing property the Zombienet config file of the Frontier Parachain Template: https://github.com/paritytech/frontier-parachain-template/blob/main/zombienet-config.toml

I am going to fix it, but in the meantime if you remove the line ` args = [""]` in the `/zombienet-config.toml` should work

**Comment by chungquantin** [comment]
@AlexD10S Thank you, I will give it a try

**Comment by AlexD10S** [comment]
I wasn't able to replicate your issue, can you share the .toml file?. 

For `fpt` parachain, it worked for me removing `args = [""] `.  I opened an issue in Zombienet-SDK repository https://github.com/paritytech/zombienet-sdk/issues/202 and the decision was to create a PR to remove `args = [""] ` in the template parity repository, so hopefully will be fixed soon.

For the `cpt` parachain I am getting a different error:
```
Could not spawn network: Orchestrator error: Provider error: File generation failed: Error: Input("Error opening spec file `contracts-parachain-local`: No such file or directory (os error 2)")
```
I am investigating it, but the repository, seems to be unmantained, so we will deprecate this parachains soon in favour of new EVM and Contracts templates chains.

**Comment by AlexD10S** [comment]
We are deprecating Parity templates in favor of Pop ones: 
<img width="606" alt="Captura de pantalla 2024-07-01 a las 10 05 47" src="https://github.com/r0gue-io/pop-cli/assets/15804380/44bc5f41-882a-4fbc-85df-45c2cf2ad5de">

To generate a contracts parachain and run it:
```
pop new parachain my_parachain -t contracts`
cd my_parachain
pop up parachain -f ./zombienet-config.toml
```

For evm parachain and run it:
```
pop new parachain evm_parachain -t evm`
cd evm_parachain
pop up parachain -f ./zombienet-config.toml
```

Both works !
