### ISSUE TITLE
feat request: add POS substrate-based chain template with `pop new parachain my-app pos`

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-cli#126]
We can customize the [`substrate-stencil`](https://github.com/kaichaosun/substrate-stencil.git) as a POP template and port out a command `pop new parachain my-app pos` to create a parachain template that has the PoS chain's features.

**Comment by weezy20** [comment]
We have thought about adding a pos template but there's two problems. This is a `solochain` template like the `substrate-node-template` and currently `pop-cli` doesn't explicitly support that. Secondly, is that repository maintained? Last commit was last year.

**Comment by brunopgalvao** [comment]
Please add a comment here: https://github.com/r0gue-io/pop-cli/issues/128

**Comment by chungquantin** [comment]
@weezy20 Yes I agree that the repo is already deprecated. But POS might be a direction that many builders who use Substrate want to use.

**Comment by brunopgalvao** [comment]
@chungquantin thanks for the feature request, I will close this issue as we would like to have feature requests here:
- https://github.com/r0gue-io/pop-cli/discussions/categories/feature-request

Can you please create a discussion there? 🙏🏻 

We will keep a running list of feature requests and see what the community "bumps" up the most.
