### ISSUE TITLE
add `--gas` and `proof-size` estimate for `pop up contract` and `pop call contract`

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#134]
Currently when using the following command:
```
pop up contract --suri //Alice --url ws://127.0.0.1:58009 
```
One needs to use other means to estimate the gas and proof-size so that they can craft the suitable params:
```
pop up contract --suri //Alice --url ws://127.0.0.1:58009 --gas 2000000000 --proof-size 1000000
```
The gas and proof-size estimate is returned in `cargo contract instantiate` I believe as a result of a dry-run.

We need pop-cli to output the estimates to the user so they do not have to run cargo-contract manually or have to resort to using the canvas UI to get the estimates.

Keep in mind the that the Pop CLI help text for `pop up contract` and `pop call contract` currently says:
```
  --gas <gas>
      Maximum amount of gas to be used for this command. If not specified it will perform a dry-run to estimate the gas consumed for the instantiation

  --proof-size <PROOF_SIZE>
      Maximum proof size for this command. If not specified it will perform a dry-run to estimate the proof size required
```

**Comment by AlexD10S** [comment]
If the user doesn't specify the gas the `pop up contract` will do a dry-run to estimate and will automatically use the estimation for the call, and display it to the user after.

```
◐  Doing a dry run to estimate the gas... 
```
```
●  Gas limit Weight { ref_time: 146346224, proof_size: 16689 }
```

Could you clarify your suggestion? Are you recommending an intermediate step to show the values to the user for confirmation before proceeding with the call?

**Comment by brunopgalvao** [comment]
> If the user doesn't specify the gas the `pop up contract` will do a dry-run to estimate and will automatically use the estimation for the call, and display it to the user after.

This only happens if the `pop up contract` command completes successfully. 

Steps to reproduce.

Clone and `cd` into the `nfts` contract in this repo: https://github.com/r0gue-io/pop-api-examples/tree/main/nfts

```
pop up contract --suri //Alice
```

Output
```
┌   Pop CLI : Deploy a smart contract
│
▲  Pre-submission dry-run failed. Add gas_limit and proof_size manually to skip this step.
│
└  Deployment failed.
```

```
```
pop up contract --suri //Alice --gas 20000 --proof-size 10000
```
┌   Pop CLI : Deploy a smart contract
│
Error: ERROR: ModuleError: Contracts::OutOfGas: ["The executed contract exhausted its gas limit."]
```
Notice that there is no estimation.
At this point, I need to to start guessing the `gas_limit`. Then finally once I guess the `gas_limit` correctly, I get this:
```
┌   Pop CLI : Deploy a smart contract
│
Error: ERROR: Rpc error: RPC error: ErrorObject { code: ServerError(1010), message: "Invalid Transaction", data: Some(RawValue("Transaction would exhaust the block limits")) }
```
So now I have to guess the `proof_size`. Eventually I get it correct and I will get a success:
```
pop up contract --suri //Alice --gas 200000000000 --proof-size 1000000
```
```
┌   Pop CLI : Deploy a smart contract
│
◇  Contract deployed and instantiated: The Contract Address is "5E13Ah9rPZNHAwpwiJLd1EQ6eVsZEmT31Cxx8oDpgTKLR21h"
│
└  Deployment complete
```
Still no estimation is shown.
