### ISSUE TITLE
Incomplete sourcing is source of errors

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#147]
```
┌   Pop CLI : Deploy a parachain
│
▲  The following missing binaries are required: polkadot-1.11.0
│  
◇  Would you like to source them automatically now?
│  Yes 
│
⚙  They will be cached at /Users/bruno/Library/Caches/pop
│  
◓  Sourcing polkadot-1.11.0...   
```

Because sourcing takes so long, it is common for the process to be halted before it is complete for whatever reason, e.g. user closes laptop lid.

Therefore, when sourcing, instead of creating the binaries out-of-the-box as they are being downloaded, rather create a temp directory (give it a hash as a name with a prefix or suffix of the version number). Only when the whole version has been "sourced", only then rename to the actual names e.g. polkadot-v1.11.0

When user re-runs, same version number command, if the temp folder exists, delete it and start over.

This will eliminate several errors which I have already encountered from incomplete sourcing.

**Comment by AlexD10S** [comment]
I believe this is outdated due to the recent improvements and fixes in the pop-up feature. I've been testing it after clearing the cache and couldn't replicate the issue. However, @brunopgalvao , I’d appreciate it if you could confirm before we close it.

**Comment by brunopgalvao** [comment]
Closing this for now. If I run into this again will re-open.
