### ISSUE TITLE
pop up parachain: build parachain if it has not been built

### ISSUE THREAD

**Issue by AlexD10S** [r0gue-io/pop-cli#176]
Similar approach of the issue pop up contract: build contract if it has not been built https://github.com/r0gue-io/pop-cli/issues/34

In this case check if the pop up needs a binary of the local chain that has not been build yet, and if this is the case builds the parachain calling https://github.com/r0gue-io/pop-cli/blob/main/crates/pop-parachains/src/build.rs#L5 

This is a bit more tricky than the pop up contract because has to parse the zombienet.toml file and see we are in the parachain folder before run build

**Comment by bolajahmad** [comment]
Please assign this to me, for some reasons I can't assign it to myself. 

[parachain label](https://github.com/r0gue-io/pop-cli/labels/parachain) is okay, but this also affects the cli. We should have a label for cli-affected issues too.

**Comment by bolajahmad** [comment]
Closing this issue as it has been fixed automatically by an [approved PR](https://github.com/r0gue-io/pop-cli/pull/199).

@AlexD10S
