### ISSUE TITLE
refactor(readme): shorten

### ISSUE THREAD

**Issue by Daanvdplas** [r0gue-io/pop-cli#183]
The readme is very heavy in terms of text while we have the pop cli docs. I suggest we do it like hardhat: https://github.com/NomicFoundation/hardhat

Basically moving all info that explains how to use pop cli to the pop cli docs and in the README provide info about pop, how to contribute, install etc.

**Comment by AlexD10S** [comment]
This was solved already in the PR: https://github.com/r0gue-io/pop-cli/pull/223
