### ISSUE TITLE
chore:  message showing parachain being build 

### ISSUE THREAD

**Issue by AlexD10S** [r0gue-io/pop-cli#188]
When building a parachain, the current message is:
```
Pop CLI : Building your parachain
```
Improve the message to display the name of the parachain being built.

Suggested by Bruno here: https://github.com/r0gue-io/pop-cli/issues/74#issuecomment-2048961689

**Comment by bolajahmad** [comment]
How can the CLI tell what the name of the parachain is? The only argument to build is the path (which can be in various form). It's not suitable as a name. Maybe a new argument to `BuildParachainCommand` but what should be the default value?

**Comment by AlexD10S** [comment]
Close with https://github.com/r0gue-io/pop-cli/pull/219
