### ISSUE TITLE
Proposal to change template licensing from Unlicense to MIT-0

### ISSUE THREAD

**Issue by aaronbassett** [r0gue-io/pop-cli#213]
Hey folks!

I propose changing the license of the various templates under r0gue control from the Unlicense to MIT-0. While I ideologically agree with the Unlicense, licensing software with the Unlicense can have the opposite effect of the desired goal; it can, in reality, make it impossible for people to use the software freely.

For more information on the problems with the unlicense, please see [PR #13465](https://github.com/paritytech/substrate/pull/13465) in the archived substrate repo.

I'm happy to make the required changes and submit PRs, but I wanted to start a discussion first, as this will require changes to several repos:

- [r0gue-io/pop-cli](https://github.com/r0gue-io/pop-cli)
- [r0gue-io/base-parachain](https://github.com/r0gue-io/base-parachain)
- [r0gue-io/pop-node](https://github.com/r0gue-io/pop-node)
- [r0gue-io/assets-parachain](https://github.com/r0gue-io/assets-parachain)
- [r0gue-io/contracts-parachain](https://github.com/r0gue-io/contracts-parachain)
- [r0gue-io/evm-parachain](https://github.com/r0gue-io/evm-parachain)

**Comment by AlexD10S** [comment]
Thanks for the suggestion! 
After checking out the resources you shared, switching the licenses of our templates to `MIT-0` sounds like a great idea:
- [r0gue-io/base-parachain](https://github.com/r0gue-io/base-parachain)
- [r0gue-io/assets-parachain](https://github.com/r0gue-io/assets-parachain)
- [r0gue-io/contracts-parachain](https://github.com/r0gue-io/contracts-parachain)
- [r0gue-io/evm-parachain](https://github.com/r0gue-io/evm-parachain)

For [r0gue-io/pop-cli](https://github.com/r0gue-io/pop-cli) we've already decided on the [GPL-3.0 license](https://github.com/r0gue-io/pop-cli?tab=GPL-3.0-1-ov-file#).
As for [r0gue-io/pop-node](https://github.com/r0gue-io/pop-node), we still need to determine the most suitable license, so let's hold off on that for now.

**Comment by AlexD10S** [comment]
Moved this Issue into the template repository, https://github.com/r0gue-io/base-parachain/issues/31

As mentioned we will change the license for the following repos:
[r0gue-io/base-parachain](https://github.com/r0gue-io/base-parachain)
[r0gue-io/assets-parachain](https://github.com/r0gue-io/assets-parachain)
[r0gue-io/contracts-parachain](https://github.com/r0gue-io/contracts-parachain)
[r0gue-io/evm-parachain](https://github.com/r0gue-io/evm-parachain)
