### ISSUE TITLE
feat: add clean all option in the `pop clean` command

### ISSUE THREAD

**Issue by AlexD10S** [r0gue-io/pop-cli#225]
With the new command `pop clean` we let the user pick what binaries to remove. Add an option in the `multiselect` to remove all the content or introduce `--all` flag.

**Comment by bolajahmad** [comment]
what binaries to remove, does this have to do with both contracts and parachain?

That means 2 commands, `pop clean contract [contract_1, ...contract_i)]` and `pop clean parachain`?

**Comment by AlexD10S** [comment]
In this PR https://github.com/r0gue-io/pop-cli/pull/216 we introduced a new command to clean the cache. You can tests it wtih `pop clean cache`. It checks the artifacts that Pop has been storing in the cache for faster development and cleans them. No need to specify contracts or parachains related, currently all are parachain binaries.
It would be good to add the `--all `flag to this command to remove all artifacts without requiring user selection.

**Comment by bolajahmad** [comment]
Assign this issue to me, I'll work on a PR.

**Comment by AlexD10S** [comment]
Cool! Thanks for the interest. Let us know if you have any doubts, and we will help you.
