### ISSUE TITLE
Thanks for using `cliclack` for TUI prompts in `pop-cli`

### ISSUE THREAD

**Issue by fadeevab** [r0gue-io/pop-cli#227]
As an author of the [`cliclack`](https://crates.io/crates/cliclack) I express my appreciation for using it in `pop-cli`. It looks awesome!

![image](https://github.com/r0gue-io/pop-cli/assets/5967447/49161d67-8dff-48f5-a964-0184c3bf7c9d)

P.S.: You can close this issue 🙂

**Comment by weezy20** [comment]
Good to see you here @fadeevab !

**Comment by fadeevab** [comment]
See you! 👋

**Comment by AlexD10S** [comment]
So happy with cliclack! It really makes our user experience much cooler!
