### ISSUE TITLE
contracts-node runs in background, easy to forget, need better UX to kill the process once done with development

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#230]
When deploying my contract using `pop up` it spins up the contracts-node in the background.

The issue is that the node continues to run in background and there is no prompt for the user to CTRL+C to kill the node once they are done with development.

**Comment by bolajahmad** [comment]
It makes sense to kill the node when done with development but how do we know when the dev is done with development?

It seems that the node is left to run in the background in case the dev wants to interact with the deployed contract, maybe we need a `pop kill` command? What are your suggestions?

**Comment by brunopgalvao** [comment]
The _correct_ way IMO is for `pop up` to output that the contract has been deployed and that contracts-node is running then hang on the terminal with an option to `CTRL+C` to kill the process.

**Comment by AlexD10S** [comment]
This PR prompts the user to kill the process when they are done testing https://github.com/r0gue-io/pop-cli/pull/248
