### ISSUE TITLE
Pop Build Parachain Asset Mint Issue

### ISSUE THREAD

**Issue by Blockcowboy2** [r0gue-io/pop-cli#251]
Parachain build with asset pallet option. 
Can not mint coin via portal. 
Asset not showing under Network.

portal: https://polkadot.js.org/apps/?rpc=ws://127.0.0.1:60332#/explorer

**Comment by AlexD10S** [comment]
Is working for me, how are you doing the mint?

A nice guide you can follow is this one: [Polkadot-JS Guides about Creating Assets](https://wiki.polkadot.network/docs/learn-guides-assets-create)

**Comment by AlexD10S** [comment]
Closing this issue as it doesn't seem to be related to `pop-cli`. If you encounter any issues with `pop-cli` again, please feel free to reopen it.
