### ISSUE TITLE
Improve Parachain Creation (Multiple Pallets)

### ISSUE THREAD

**Issue by Blockcowboy2** [r0gue-io/pop-cli#252]
Allow multiple pallets to be added to a Parachain creation e.g. Asset + Contract.

 pop new parachain --template    <TEMPLATE>
  [possible values: standard, assets, contracts, evm, polkadot-generic-runtime-template, cpt, fpt]

Not working, instead it gives choices below which do not allow selection of multiple types (combined)

┌   Pop CLI : Generate a parachain
│
◇  Select a template provider: 
│  Pop 
│
◆  Select the type of parachain:
│  ● Standard (A standard parachain)
│  ○ Assets 
│  ○ Contracts 
│  ○ EVM

**Comment by AlexD10S** [comment]
Thank you for the suggestions. We're currently improving Pop CLI based on user feedback. 
I am not sure i understand what is not working, you can see the documentation of our current features here: https://learn.onpop.io/v/appchains

We have plans to add functionality for incorporating extra pallets into parachains, so stay tuned for upcoming updates!

**Comment by AlexD10S** [comment]
Closing this issue as it doesn't seem to be related to `pop-cli`. If you encounter any issues with `pop-cli `again, please feel free to reopen it.
