### ISSUE TITLE
Improve template pallet generation

### ISSUE THREAD

**Issue by tsenovilla** [r0gue-io/pop-cli#253]
Currently, the command 
```bash
pop new pallet
```
is just creating a static template. IMO, this command would be more useful if it provided the user with an interactive interface to design its pallet template according to its needs (eg, how many storage items are needed, does the user wanna a default configuration template for the config trait to be included?, ...). Otherwise, it's almost the same as publishing the template on Github. 

The main point here is to decide where we draw the line. If this interactive interface offers too much, it may become useless. For example, if it forces the user to add all the config types with their trait bounds, there wouldn't be much difference compared to writing it directly on the pallet, and the process will get longer and boring for the user❌. In the other hand, if it just offers the possibility to write the names of those (or some of them) types, the process is more straightforward and the user may be attracted to use the CLI by the fact of creating a template with at least some structure in its config trait, without spending so much time in defining all the trait bounds in the CLI, that can be done later.

IMO, there should be an equilibrium making this tool attractive for the user in terms of time, as well as offering the ability of customizing a little bit the template from the CLI, instead of using a static template. 

I'm already working on a potential solution 😆 will PR it asap!

**Comment by evilrobot-01** [comment]
Agreed, the pallet story definitely needs some love and is next up on our roadmap, starting with adding existing pallets to a runtime. I think you nailed the balance that we strive for, so really looking forward to your PR!

**Comment by AlexD10S** [comment]
Closed with https://github.com/r0gue-io/pop-cli/pull/261
