### ISSUE TITLE
avoid linking to substrate.io

### ISSUE THREAD

**Issue by kianenigma** [r0gue-io/pop-cli#260]
I see that the pallet template links a lot to substrate.io, and I want to suggest you to update to linking to better rust-docs instead of those. 

PaperMoon and a few other areas already in the process of deprecating the website. 

I have worked with Daan already to show that a pallet template can be "backed" by links to polkadot-sdk-docs in a reasonably good way, for example https://github.com/paritytech/polkadot-sdk/pull/4684/files

related https://github.com/paritytech/polkadot-sdk/pull/5118

**Comment by tsenovilla** [comment]
Hey @kianenigma 😄. I've been working in the pallet template these days and just submitted a PR:

-  #261 

In this version there's no links to substrate.io but to the polkadot-sdk-docs. I haven't included a link for everything though, just a link to those docs. I can update it to include some other links and include the same PR with this issue

**Comment by AlexD10S** [comment]
Closed with https://github.com/r0gue-io/pop-cli/pull/272
