### ISSUE TITLE
Command Deprecated - Web Page update required

### ISSUE THREAD

**Issue by Blockcowboy2** [r0gue-io/pop-cli#268]
Web Page needs update:

https://learn.onpop.io/v/contracts/guides/deploying-your-contract-locally

pop build contract

   Pop CLI : Building your contract
│
▲  NOTE: this command is deprecated. Please use `pop build` (or simply `pop b`) in future...

**Comment by AlexD10S** [comment]
Thanks for reporting this. I am closing this issue and opening a new one in the documentation repository (See here: https://github.com/r0gue-io/pop-docs/issues/7), as it is related to that repository. We'll update it as soon as possible.

**Comment by Blockcowboy2** [comment]
Apology. I will place in right place next time. Thanks.

**Comment by AlexD10S** [comment]
No problem. The docs has been updated thanks to your report: https://learn.onpop.io/v/contracts/guides/build-your-contract
