### ISSUE TITLE
feat: show contract-node's node logs for debugging purposes

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#291]
It is often the case that when I am debugging ink! smart contracts, I use [ink::env::debug_println!](https://docs.rs/ink_env/4.0.0/ink_env/macro.debug_println.html) which shows up in the contract-node's node logs. Currently Pop CLI does not offer a way to see my node logs which is a deal-breaker for ink! smart contract development.

Ask: Need a way to access to contract-node’s node logs for debugging.

Also, please make sure that when contract node is spun up with the debug flags:
e.g. `substrate-contracts-node -lerror,runtime::contracts=debug`

- https://use.ink/basics/contract-debugging

Looking at node logs is also useful for debugging certain types of errors.

**Comment by AlexD10S** [comment]
Closed in https://github.com/r0gue-io/pop-cli/pull/330
