### ISSUE TITLE
feat(docs): parachain template README file should show guidelines & resources

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-cli#300]
The command `pop new parachain` has a perfect "Next Steps" section.
```
◆  Generation complete
│  Version: polkadot-v1.12.0
│  
▲  NOTE: the resulting parachain is not guaranteed to be audited or reviewed for security vulnerabilities.
│  Please consult the source repository at https://github.com/r0gue-io/assets-parachain to assess production suitability and licensing restrictions.
│  
◆  Next Steps:
│  ● cd into "scaling-substrate-guide" and enjoy hacking! 🚀
│  ● Use `pop build` to build your parachain.
│  ● Use `pop up parachain -f ./network.toml` to launch your parachain on a local network.
```
But the README.md is quite simple at the moment

<img width="646" alt="Screenshot 2024-09-01 at 12 02 07" src="https://github.com/user-attachments/assets/17078448-7cc3-471e-ab1d-9ea0c0584cd8">

I suggest improving the README.md by adding more guides to the README.md which will makes our Parachain templates more newcomer-friendly. The impact of the README.md is huge and can make `pop-cli` parachain template as the go-to tool for any new Substrate developers

**Comment by AlexD10S** [comment]
Our approach was to keep the `README` cleaner by providing links to our extensive documentation page. However, I see your point. What specific information or sections would you suggest adding to the `README` to make it more useful?

**Comment by chungquantin** [comment]
```
│  ● Use `pop build` to build your parachain.
│  ● Use `pop up parachain -f ./network.toml` to launch your parachain on a local network.
```
@AlexD10S For example, adding these commands like this in the README is very helpful. Because let say if the user closes the terminal or when they are working on the parachain, instead of visiting the POP CLI doc site, they can simply find these common commands rightaway in the README file.

**Comment by AlexD10S** [comment]
Makes sense to me. I see there is already a pending PR in the `base-parachain` including this fix: https://github.com/r0gue-io/base-parachain/pull/46/files

**Comment by AlexD10S** [comment]
The PR has been merged: https://github.com/r0gue-io/base-parachain/pull/46, so this can be closed. The changes will be included in upcoming releases.
