### ISSUE TITLE
chore: use chain spec generator from paseo-network-runtimes

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#301]
So currently in our latest release (and `main`), I cannot get a standard parachain created with Pop CLI to produce blocks on `paseo-local`. But if I replace the chain spec generator that Pop CLI pulls with this one: https://github.com/r0gue-io/paseo-network-runtimes/releases/tag/v1.2.5 it works.

**Comment by AlexD10S** [comment]
Fixed with the new release: https://github.com/r0gue-io/paseo-runtimes/releases/tag/v1.2.6
