### ISSUE TITLE
`Bootnode with peer id `...` is on a different chain (our genesis: 0x71f2…6be1 theirs: 0xfcc8…846b)`

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#308]
When running a collator to sync with a Pop CLI spun-up Paseo network locally I get the following error: 
```
[Relaychain] Bootnode with peer id `12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm` is on a different chain (our genesis: 0x71f2…6be1 theirs: 0xfcc8…846b) 
```

### Steps to reproduce:

On `main`, use Pop CLI to spin up a Paseo network: 

network.toml
```toml
[relaychain]
chain = "paseo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true
```
```
pop up parachain -f network.toml
```

Download the `1.2.6` paseo-local raw chain spec from: https://github.com/r0gue-io/paseo-runtimes/tree/v1.2.6

Use this chain spec to run a collator to sync with the running Paseo network:

```
./target/release/parachain-template-node \
--collator \
--force-authoring \
--chain chain-spec-raw.json \
--base-path ./data \
--port 40333 \
--rpc-port 8845 \
--name "Awesome Collator" \
-- \
--sync warp \
--execution wasm \
--chain paseo-local.raw.json \
--port 64904 \
--rpc-port 57577 \
--bootnodes /ip4/127.0.0.1/tcp/57578/p2p/12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm
```
You will see the following error:
```
[Relaychain] Bootnode with peer id `12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm` is on a different chain (our genesis: 0x71f2…6be1 theirs: 0xfcc8…846b) 
```
The paseo local raw chain spec that Pop CLI pulls is different than what is found in:
- https://github.com/r0gue-io/paseo-runtimes/tree/v1.2.6

Diff can be found here: https://github.com/brunopgalvao/my-parachain/pull/1

As a developer who is testing a collator and therefore I need a matching Paseo local chain spec to the Paseo local chain spec that `pop up parachain -f network.toml` uses, I need to know what version of the Paseo chain spec Pop CLI is using so I can download the same one from https://github.com/r0gue-io/paseo-runtimes

**Comment by al3mart** [comment]
After reviewing this with @brunopgalvao it seems that there was a misconfig on the ports.

@brunopgalvao feel free to leave this one open if you feel that we might need it again before the tutorial is merged.
Otherwise it looks like we could close it already.

**Comment by brunopgalvao** [comment]
Thank you a million @al3mart! Closing for now.
