### ISSUE TITLE
Add `CONTRACTS_NODE_PATH` to Pop when running e2e tests for contracts

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#31]
Based on this PR comment: https://github.com/r0gue-io/pop-cli/pull/22#issuecomment-1980361632

The idea would be devs can run e2e tests like this:
```
pop test contract  -p ./my_contract --features e2e-tests -n /Users/bruno/src/substrate-contracts-node/target/debug/substrate-contracts-node
```

**Comment by AlexD10S** [comment]
When this PR is merged https://github.com/r0gue-io/pop-cli/pull/185 can we just call that functionality to run the local node?
