### ISSUE TITLE
feat: add support to Zombienet's `ws_port` config option

### ISSUE THREAD

**Issue by juangirini** [r0gue-io/pop-cli#314]
When specifying the `ws_port` under `[[parachains.collators]]` or `[[relaychain.nodes]]` in `network.toml` this configuration does nothing. Unlike in Zombienet where this option would define the node's ws port.

Ideally, this should work just like Zombienet.

**Comment by pepoviola** [comment]
Is this still needed? I can take a look. Thx!

**Comment by pepoviola** [comment]
Ahh, sorry about the delay. @juangirini we drop the `ws_port` in favor of `rpc_port` since `--ws-port` is also deprecated in the client. Can you switch to use `--rcp-port`?
Thanks and sorry about the delay/noice.

**Comment by juangirini** [comment]
alright, thanks a lot @pepoviola and sorry for opening this issue
