### ISSUE TITLE
Pop-CLI is big !

### ISSUE THREAD

**Issue by weezy20** [r0gue-io/pop-cli#32]
Currently, while developing and having RA on `default-features` (target) take up some 22.8 GB on my machine. We should explore ways to reduce build times, and possibly shave off heavy dependencies. 

A fresh build from no target, takes up 6.9 GB.

**Comment by weezy20** [comment]
@brunopgalvao I believe the `up` feature is heavy now due to the deps on zombienet-sdk and related which pulls in a lot of unnecessary crates.

**Comment by brunopgalvao** [comment]
What can be done?

In future, could we have zombienet-sdk in the cloud so that when we call `pop up` it uses git to push up the changes and deploys in a cloud environment?

e.g. this would be a Pop+ feature
