### ISSUE TITLE
pop not fetching latest client when run with pop up parachain -f file.yaml

### ISSUE THREAD

**Issue by hitchhooker** [r0gue-io/pop-cli#325]
```
w3reg@w3reg  𓅨 ~ ➤ 789cb27|w3reg⚡
1871 ± pop up parachain -f tests/networks/rococo+people.toml  
┌   Pop CLI : Launch a local network
│
▲  ℹ️ The following binaries have newer versions available:
│     > polkadot v1.13.0 -> v1.14.0, polkadot-parachain v1.13.0 -> v1.14.0
│
◇  📦 Would you like to source them automatically now? It may take some time...
│  Yes
│
⚙  ℹ️ Binaries will be cached at /home/w3reg/.cache/pop
│
◆  📦 Sourcing binaries...                                                                                                                                     │  ◓ polkadot: Extracting from archive...
│  ◐ polkadot-parachain: waiting...
```

w3reg@w3reg  𓅨 ~ ➤ 789cb27|w3reg⚡
1872 ± pop --version                                                                                                                             ⏎ [64d19h2m] ✹
pop-cli 0.4.0

,pop new parachain offers stable client
![image](https://github.com/user-attachments/assets/24154204-28ac-4d56-95d7-b67110a8d664)

![image](https://github.com/user-attachments/assets/e698ac5d-462d-432b-9979-f7843fe99140)

just seem incredibly hard to get latest client 1.16/stable

**Comment by hitchhooker** [comment]
this feels like sorting issue in sourcing  prioritizing number versioned over stable2409

**Comment by AlexD10S** [comment]
Thanks for reporting. I am investigating why is not getting the `stable2409` as the latest one. For now you can fetch it using `-r stable2409`. For example:  `pop up parachain -f network.toml -r stable2409`

**Comment by hitchhooker** [comment]
i also tried to sort it, passing all test but somehow it kept offering semver ones. but yeah -r flag solves it for me
