### ISSUE TITLE
`pop up contract`: run substrate-contracts-node if it does not exist

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#35]
Based on this PR comment: https://github.com/r0gue-io/pop-cli/pull/27#discussion_r1515973155

For `pop up contract`, we should do a check, if there is no substrate node running on localhost:9944 then have Pop CLI run one.

**Comment by AlexD10S** [comment]
Same as commented here: https://github.com/r0gue-io/pop-cli/issues/31#issuecomment-2124252867
When this PR is merged https://github.com/r0gue-io/pop-cli/pull/185 we can just call that functionality to run the local node
