### ISSUE TITLE
`pop build contract`: add default contracts directory

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#42]
As a dev, I would like to have a seamless UX flow for building contracts in which I created with Pop, so that I don't have to waste time specifying configuration that should already by part of the Pop flow.

The UX flow for building contracts with Pop should be the following:
```
pop new contract my_contract
```
```
pop build contract my_contract
```
Currently it is not so, currently this is the flow:
```
pop new contract my_contract
```
```
pop build contract -p ./my_contract
```

`-p` should be an optional argument when the developer is storing their contracts in another directory other than the default.

**Comment by Daanvdplas** [comment]
I would even add to this that when the dev is in the repo of the contract it should be able to run `pop build` and pop cli will detect that it is in a contract folder and run `cargo contract build` under the hood.

Detecting whether the dev wants to execute a pop cli command on parachain / contract folder will be useful in general.

**Comment by brunopgalvao** [comment]
> I would even add to this that when the dev is in the repo of the contract it should be able to run `pop build` and pop cli will detect that it is in a contract folder and run `cargo contract build` under the hood.
> 
> 
> 
> Detecting whether the dev wants to execute a pop cli command on parachain / contract folder will be useful in general.

whao I like this `pop build`

**Comment by AlexD10S** [comment]
Closing this Issue as it will be solved with this one: https://github.com/r0gue-io/pop-cli/issues/91
