### ISSUE TITLE
`pop new parachain`: remove pallet template from base template

### ISSUE THREAD

**Issue by Daanvdplas** [r0gue-io/pop-cli#54]
When executing `pop new parachain` we don't want there to be a 
- [x] `template` folder in `pallets`
- [x] remove `pallet_parachain_template` from `runtime/src/lib.rs`
- [x] remove " " from `Cargo.toml`
- [x] remove " " from `runtime/Cargo.toml`

**Comment by weezy20** [comment]
We cannot remove `pallets/template` that's used to generate a new pallet with `pop new pallet`

**Comment by AlexD10S** [comment]
Closed with https://github.com/r0gue-io/pop-cli/pull/57
