### ISSUE TITLE
Branch `add-pallet` needs to check for duplicated entries.

### ISSUE THREAD

**Issue by al3mart** [r0gue-io/pop-cli#63]
The command `pop add pallet` in branch `add-pallet` will inject the different features for the pallet independently of these being already present in the file.

This can be reproduce by running twice the same command, for instance: `pop add pallet template -r runtime/src/lib.rs` within a parachain project.

It will also instantiate multiple times the same pallet in the runtime.

**Comment by evilrobot-01** [comment]
The entry API to toml_edit could be useful for this: https://github.com/r0gue-io/pop-cli/blob/7dc2e5ddf7765f3e44730d438e6cb9931864db42/src/parachains/zombienet.rs#L148-L149

**Comment by AlexD10S** [comment]
I close the issue for now as we still don't have the` pop add pallet` functionality
