### ISSUE TITLE
UX: `pop build parachain` to support multiple parachains

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#74]
```
pop new parachain my-good-chain
```
```
pop new parachain my-better-chain
```
The issue is when I run:
```
pop build parachain
```
IIUC, there is no way to specify which chain I want to build.

Also, the message will show:
```
┌   Pop CLI : Building a parachain
```
The message should have the parachain name.

**Comment by weezy20** [comment]
Related #9

**Comment by AlexD10S** [comment]
Are you suggesting to run `pop build parachain` and build all parachains it finds in the repo?  Is that needed? 

Build the 2 parachains right now is just 2 commands, clear enough for me.
```
pop build parachain --p my-good-chain
pop build parachain --p my-better-chain
```

**Comment by brunopgalvao** [comment]
I think this is no longer an issue but we should say in the output which parachain the CLI is building
