### ISSUE TITLE
Feature: Cache management

### ISSUE THREAD

**Issue by evilrobot-01** [r0gue-io/pop-cli#78]
`pop up parachain` currently sources polkadot/system parachain binaries and caches them for subsequent runs. The user should be able to easily see and clear what is in the cache.

Note that this was already implemented in a previous version of the tool, so I will just port it over. We just need to align on the command structure which can allow reuse for other related functionality - e.g. inspect: `pop inspect cache`, clear: `pop clear cache`

**Comment by AlexD10S** [comment]
When doing this consider this issue: https://github.com/r0gue-io/pop-cli/issues/96 and remove `/Library/Caches/pop/.src/polkadot-sdk` folder too

**Comment by evilrobot-01** [comment]
> When doing this consider this issue: #96 and remove `/Library/Caches/pop/.src/polkadot-sdk` folder too

Note that `/cache/pop/.src` is no longer used. Prebuilt binaries are sourced where possible, and if from a git repository then they are built in a temp directory: https://github.com/r0gue-io/pop-cli/blob/baacdd35f04830094efb9e6afc989f722934ae5f/crates/pop-parachains/src/up/sourcing.rs#L260 and https://github.com/r0gue-io/pop-cli/blob/baacdd35f04830094efb9e6afc989f722934ae5f/crates/pop-parachains/src/up/sourcing.rs#L334
