### ISSUE TITLE
Cargo test takes too long to test

### ISSUE THREAD

**Issue by weezy20** [r0gue-io/pop-cli#88]
Somewhat related to #81 and others, but `cargo test` is supposed to check and provide quick feedback for core features of `pop` for developers of pop rather than end-users. Since we are now building and checking a contract and a parachain when running `cargo test` it's extremely inefficient to check for coding errors when working on any feature.

Either feature gate or `#[ignore]` these long running tests so that they can be manually run by interested people, rather than having it run by default on `cargo test`. 

Additionally, modify CI to include `#[ignore]`'d tests if so desired. 

Also something worth considering is why are these tests not a part of the parachain/contract templates themselves?

**Comment by brunopgalvao** [comment]
For e2e tests, I would not be against having a separate repo that has all the e2e test code which has a CI which runs independently from pop-cli repo.

**Comment by AlexD10S** [comment]
Close with https://github.com/r0gue-io/pop-cli/pull/90
