### ISSUE TITLE
Pop Build - Parachain/Contract cargo project detection on current working dir

### ISSUE THREAD

**Issue by weezy20** [r0gue-io/pop-cli#91]
A discussion rather than an issue.

Currently, if `pop build` is invoked without a `path`, it builds any cargo project in the current working dir: 
```rs
pub fn build_parachain(path: Option<PathBuf>) -> anyhow::Result<()> {
	cmd("cargo", vec!["build", "--release"])
		.dir(path.clone().unwrap_or("./".into()))
		.run()?;
	Ok(())
}
```
This is fine if the current working dir is a parachain project, but is unexpected or unintended behaviour when invoked in some other cargo project. `pop build`, for the sake of correctness, should be ideally scoped only to build `contract` and `parachain` cargo projects. 
I understand that this is not really a problem, but this issue is meant for discussion on if it's worth the additional code or not.

**Comment by AlexD10S** [comment]
Is a good point, as you mention `pop-cli` should be scoped only to build `contract` and `parachain` cargo projects. So I am in favor of adding a check and show an error to the user if the path is not a `contract` or `parachain` project

**Comment by Daanvdplas** [comment]
Yes agreed, I think checking for contract / parachain specific files in the root of the project is a start. E.g.:
1. contract: `Cargo.toml` file with ink depenedency
2. parachain: `node/`, `runtime/` folders

**Comment by weezy20** [comment]
@Daanvdplas I like the approach. I believe that we should do the same as in contracts, i.e. check for substrate linked dependencies, such as `frame-support` or `frame-system` for runtime and `sc-*` deps for node. We could also check for the folder structure `node/`, `runtime/`, however a weird edge case might be someone uses `pop build` with a substrate project that calls them `my-node` and `my-runtime`. It's good to think of solutions that can handle worst possible case.

**Comment by Daanvdplas** [comment]
I have never seen a project where the folders are not called `node/` and `runtime/`. Therefore I suggest we keep it simple and start with the above approach. Time will tell if we need more advanced searching

**Comment by weezy20** [comment]
@Daanvdplas quick example:
1. https://github.com/Polkadex-Substrate/Polkadex. 
2. https://github.com/paseo-network/runtimes
3. https://github.com/aleph-zero-foundation/aleph-node
As you can see, projects using multiple implementations in this case can call it something else:  `nodes`, `runtimes` or even have it in separate repositories. It's unwise to assume every substrate project would follow the same directory naming conventions.

**Comment by Daanvdplas** [comment]
Oke, perhaps a dependency like `sp-runtime` (found it in the node and runtime after having a quick look) ?
